// Copyright 2014 The go-gl/mathgl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build ignore

// codegen generates go code from templates. Intended to be
// used with go generate; see the invocation in vectorStatic.go.

package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

type Context struct {
	Comment      string
	TemplateName string
}

func main() {
	var tplPath = flag.String("template", "vector.tpl", "template name")
	var oPath = flag.String("output", "vector.go", "file name to write")

	flag.Parse()
	if flag.NArg() > 0 {
		fmt.Println("usage: codegen -template path -output path")
		os.Exit(1)
	}

	tpl := template.New("").Delims("<<", ">>").Funcs(template.FuncMap{
		"typename":    typenameHelper,
		"elementname": elementNameHelper,
		"iter":        iterHelper,
		"enum":        enumHelper,
	})
	tpl = template.Must(tpl.ParseFiles(*tplPath))
	tplName := filepath.Base(*tplPath)

	oFile, err := os.Create(*oPath)
	if err != nil {
		panic(err)
	}

	context := Context{
		Comment:      "This file is generated by codegen.go; DO NOT EDIT",
		TemplateName: tplName,
	}
	err = tpl.ExecuteTemplate(oFile, tplName, context)
	if err != nil {
		panic(err)
	}

	oFile.Close()

	fmtOutput, err := exec.Command("go", "fmt", *oPath).CombinedOutput()
	if err != nil {
		os.Stdout.Write(fmtOutput)
		panic(err)
	}
}

func typenameHelper(m, n int) string {
	if m == 1 {
		return fmt.Sprintf("Vec%d", n)
	}
	if n == 1 {
		return fmt.Sprintf("Vec%d", m)
	}
	if m == n {
		return fmt.Sprintf("Mat%d", m)
	}
	return fmt.Sprintf("Mat%dx%d", m, n)
}

func elementNameHelper(m int) string {
	switch m {
	case 0:
		return "X"
	case 1:
		return "Y"
	case 2:
		return "Z"
	case 3:
		return "W"
	default:
		panic("Can't generate element name")
	}
}

func iterHelper(start, end int) []int {
	iter := make([]int, end-start)
	for i := start; i < end; i++ {
		iter[i] = i
	}
	return iter
}

// Template function that returns slice from its arguments. Indended to be used
// in range loops.
func enumHelper(args ...int) []int {
	return args
}
