sudo: false
language: go
go:
  - 1.12.x
  - 1.11.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - go test -v -race ./...
