language: go

go:
 - 1.2

script:
 - go test -v ./mgl32
 - go test -v ./mgl64
 - diff -u <(echo -n) <(gofmt -d ./)

after_failure: failure
after_error: failure

notifications:
  email:
    recipients:
      - jragonmiris@gmail.com
    on_success: change
    on_failure: always
